---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-nginx
  name: sample-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - image: 779385874783.dkr.ecr.us-west-2.amazonaws.com/ecr-public/nginx/nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: sample-nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-nginx
  name: sample-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-nginx
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-nginx
                port:
                  number: 80